name: Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: sudo apt-get -y install valgrind 
    - name: memcheck
      run: valgrind ./M1_EVcalculation/3_Implementation//build/Test_EVcalculator.out
